import { Router } from "express";
import { BusinessRouter } from "./business.routes.ts";
import { EmployeeRouter } from "./employee.routes.ts";
import { EmployeeUnavailabilityRouter } from "./employeeUnavailability.routes.ts";
import { PermissionRoleRouter } from "./permissionRole.routes.ts";
import { RoleRouter } from "./role.routes.ts";
import { ScheduleTemplateRouter } from "./scheduleTemplate.routes.ts";
import { SettingsRouter } from "./settings.routes.ts";
import { ShiftRouter } from "./shift.routes.ts";
import { ShiftOfferRequestRouter } from "./shiftOfferRequest.routes.ts";
import { ShiftTradeRequestRouter } from "./shiftTradeRequest.routes.ts";
import { TaskRouter } from "./task.routes.ts";
import { TaskListRouter } from "./taskList.routes.ts";
import { TimeOffRequestRouter } from "./timeOffRequest.routes.ts";
import { TimeSheetRouter } from "./timeSheet.routes.ts";
import { UserRouter } from "./user.routes.ts";
import { ScheduleShiftTemplateRouter } from "./scheduleShiftTemplate.routes.ts";
import { SessionRouter } from "./session.routes.ts";
import { TaskListTemplateRouter } from "./taskListTemplate.routes.ts";
import { TaskTemplateRouter } from "./taskTemplate.routes.ts";

const router = Router();

router.use("/businesses", BusinessRouter);
router.use("/employees", EmployeeRouter);
router.use("/employeeUnavailabilities", EmployeeUnavailabilityRouter);
router.use("/permissionRoles", PermissionRoleRouter);
router.use("/roles", RoleRouter);
router.use("/scheduleShiftTemplates", ScheduleShiftTemplateRouter);
router.use("/scheduleTemplates", ScheduleTemplateRouter);
router.use("/sessions", SessionRouter);
router.use("/settings", SettingsRouter);
router.use("/shifts", ShiftRouter);
router.use("/shiftOfferRequests", ShiftOfferRequestRouter);
router.use("/shiftTradeRequests", ShiftTradeRequestRouter);
router.use("/tasks", TaskRouter);
router.use("/taskLists", TaskListRouter);
router.use("/taskListTemplates", TaskListTemplateRouter);
router.use("/taskTemplates", TaskTemplateRouter);
router.use("/timeOffRequests", TimeOffRequestRouter);
router.use("/timeSheets", TimeSheetRouter);
router.use("/users", UserRouter);

export { router };
